---
dependency:
  name: galaxy
driver:
  name: docker


lint:
  name: yamllint
platforms:
  - name: centos-7
    image: centos:7
    privileged: true
    command: /usr/lib/systemd/systemd

  - name: ubuntu-xenial
    image: ubuntu:16.04
    privileged: true
    command: /lib/systemd/systemd

  - name: ubuntu-trusty
    image: ubuntu:14.04
    command: /sbin/init
    privileged: true

  - name: ubuntu-precise
    image: ubuntu:12.04
    command: /sbin/init
    privileged: true

provisioner:
  name: ansible
  lint:
    name: ansible-lint
scenario:
  name: default
verifier:
  name: testinfra
  lint:
    name: flake8
