# Molecule managed

---
all:
  hosts:
    centos-7: &id001
      ansible_connection: docker
    ubuntu-precise: &id002
      ansible_connection: docker
    ubuntu-trusty: &id003
      ansible_connection: docker
    ubuntu-xenial: &id004
      ansible_connection: docker
ungrouped:
  hosts:
    centos-7: *id001
    ubuntu-precise: *id002
    ubuntu-trusty: *id003
    ubuntu-xenial: *id004
  vars: {}
